config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja/ do
    devise_for :users, skip: :omniauth_callbacks, path_names: {
      sign_in: 'login',
      sign_out: 'logout',
    }
    match "/users/auth/:provider",
      constraints: { provider: /google|facebook/ },
      to: "devise/omniauth_callbacks#passthru",
      as: :omniauth_authorize,
      via: [:get, :post]
    match "/users/auth/:action/callback",
      constraints: { action: /google|facebook/ },
      to: "devise/omniauth_callbacks#:action",
      as: :omniauth_callback,
      via: [:get, :post]
    devise_scope :user do
      get 'users/logout' => 'devise/sessions#destroy'
      get 'logout' => 'devise/sessions#destroy'
    end

    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: '/letter_opener'
    end

    controller :welcome do
      get 'hoe'
      get 'about'
      get 'contact'
      get 'team'
    end

    resources :bugs

    resources :posts

    resources :comments

    root 'welcome#index'
  end
end

app/models/bug.rb
# coding: utf-8
class Bug < ActiveRecord::Base
  belongs_to :bug
  has_many :post_bugs
  has_many :posts, through: :post_bugs

  validates :name, uniqueness: true
  validates :keyname, uniqueness: true

  def to_param
    keyname
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]

  def index
    @bugs = Bug.all
  end

  def show
  end

  def new
    @bug = Bug.new
  end

  def edit
  end

  def create
    @bug = Bug.new(bug_params)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bug
      @bug = Bug.find_by_keyname(params[:id])
    end

    def bug_params
      params.require(:bug).permit(:bug_id, :name, :keyname)
    end
end

app/views/bugs/_form.html.slim
= simple_form_for(@bug) do |f|
  = f.error_notification

  .form-inputs
    = f.association :bug
    = f.input :name
    = f.input :keyname

  .form-actions
    = f.button :submit

app/views/bugs/edit.html.slim
h1 Editing bug

== render 'form'

= link_to 'Show', @bug
'|
= link_to 'Back', bugs_path

app/views/bugs/index.html.slim
h1 Listing bugs

table.table
  thead
    tr
      th Bug
      th Name
      th Keyname
      th
      th
      th

  tbody
    - @bugs.each do |bug|
      tr
        td = bug.bug
        td = bug.name
        td = bug.keyname
        td = link_to 'Show', bug
        td = link_to 'Edit', edit_bug_path(bug)
        td = link_to 'Destroy', bug, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Bug', new_bug_path

app/views/bugs/new.html.slim
h1 New bug

== render 'form'

= link_to 'Back', bugs_path

app/views/bugs/show.html.slim
p
  strong Bug:
  = @bug.bug
p
  strong Name:
  = @bug.name
p
  strong Keyname:
  = @bug.keyname

= link_to 'Edit', edit_bug_path(@bug)
'|
= link_to 'Back', bugs_path