config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja/ do
    devise_for :users, skip: :omniauth_callbacks, path_names: {
      sign_in: 'login',
      sign_out: 'logout',
    }
    match "/users/auth/:provider",
      constraints: { provider: /google|facebook/ },
      to: "devise/omniauth_callbacks#passthru",
      as: :omniauth_authorize,
      via: [:get, :post]
    match "/users/auth/:action/callback",
      constraints: { action: /google|facebook/ },
      to: "devise/omniauth_callbacks#:action",
      as: :omniauth_callback,
      via: [:get, :post]
    devise_scope :user do
      get 'users/logout' => 'devise/sessions#destroy'
      get 'logout' => 'devise/sessions#destroy'
    end

    if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: '/letter_opener'
    end

    controller :welcome do
      get 'hoe'
      get 'about'
      get 'contact'
      get 'team'
    end

    resources :bugs

    resources :posts

    resources :comments

    root 'welcome#index'
  end
end

app/views/layouts/BAK._header.html.erb
<div class="navbar-wrapper mbxl">
	<div class="container">

		<div class="navbar navbar-default navbar-fixed-top" role="navigation" id="top-nav">
			<div class="container">
				<div class="navbar-header">
					<!-- Logo Starts -->
					<%= link_to root_path, class: 'navbar-brand' do %>
						<%= image_tag 'logo.png', alt: 'logo', size: '230x54' %>
					<% end %>
					<!-- #Logo Ends -->
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>

				<!-- Nav Starts -->
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to 'Home', root_path, class: 'active' %></li>
						<li><%= link_to 'About', about_path %></li>
						<li><%= link_to 'Contact', contact_path %></li>
						<li><%= link_to 'Team', team_path %></li>
						<% if current_user %>
							<li><%= link_to 'Sign out', destroy_user_session_path %></li>
						<% else %>
							<li><%= link_to 'Sign in', new_user_session_path %></li>
							<li><%= link_to 'Sign up', new_user_registration_path %></li>
						<% end %>
					</ul>
				</div>
				<!-- #Nav Ends -->

			</div>
		</div>
	</div>
</div>

app/views/layouts/BAK.application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<title>Bug &times; Bug</title>
		<!-- stylesheets -->
		<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= stylesheet_link_tag 'style' %>
		<%= yield :css %>
		<!-- javascripts -->
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'script' %>
		<%= csrf_meta_tags %>
		<%= yield :js %>
		<!-- favicon -->
		<link rel="shortcut icon" href="<%= asset_path 'favicon.ico' %>" type="image/x-icon">
		<link rel="icon" href="<%= asset_path 'favicon.ico' %>" type="image/x-icon">
	</head>

	<body>
		<div class="topbar animated fadeInLeftBig"></div>

		<%= render 'layouts/header' %>

		<% if flash[:alert] %>
			<div class="alert alert-dismissible alert-danger" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<%= alert %>
			</div>
		<% elsif flash[:notice] %>
			<div class="alert alert-dismissible alert-success" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<%= notice %>
			</div>
		<% end %>

		<% if @full_screen_width %>
			<%= yield %>
		<% else %>
			<div class="container" style="margin-top: 100px;">
				<%= yield %>
			</div>
		<% end %>
	</body>
</html>

app/views/layouts/_header.html.erb
<div class="navbar-wrapper mbxl">
	<div class="container">

		<div class="navbar navbar-default navbar-fixed-top" role="navigation" id="top-nav">
			<div class="container">
				<div class="navbar-header">
					<!-- Logo Starts -->
					<%= link_to root_path, class: 'navbar-brand' do %>
						<%= image_tag 'logo.png', alt: 'logo', size: '230x54' %>
					<% end %>
					<!-- #Logo Ends -->
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>

				<!-- Nav Starts -->
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to 'Home', root_path, class: 'active' %></li>
						<li><%= link_to 'About', about_path %></li>
						<li><%= link_to 'Contact', contact_path %></li>
						<li><%= link_to 'Team', team_path %></li>
						<% if current_user %>
							<li><%= link_to 'Sign out', destroy_user_session_path %></li>
						<% else %>
							<li><%= link_to 'Sign in', new_user_session_path %></li>
							<li><%= link_to 'Sign up', new_user_registration_path %></li>
						<% end %>
					</ul>
				</div>
				<!-- #Nav Ends -->

			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<title>Bug &times; Bug</title>
		<!-- stylesheets -->
		<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= stylesheet_link_tag 'style' %>
		<%= yield :css %>
		<!-- javascripts -->
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'script' %>
		<%= csrf_meta_tags %>
		<%= yield :js %>
		<!-- favicon -->
		<link rel="shortcut icon" href="<%= asset_path 'favicon.ico' %>" type="image/x-icon">
		<link rel="icon" href="<%= asset_path 'favicon.ico' %>" type="image/x-icon">
	</head>

	<body>
		<div class="topbar animated fadeInLeftBig"></div>

		<%= render 'layouts/header' %>

		<% if flash[:alert] %>
			<div class="alert alert-dismissible alert-danger" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<%= alert %>
			</div>
		<% elsif flash[:notice] %>
			<div class="alert alert-dismissible alert-success" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<%= notice %>
			</div>
		<% end %>

		<% if @full_screen_width %>
			<%= yield %>
		<% else %>
			<div class="container">
				<%= yield %>
			</div>
		<% end %>
	</body>
</html>

app/views/layouts/application.slim
doctype html
html
  head
    title
      | Known Issues
    link[rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"]
    = stylesheet_link_tag 'application', media: 'all'
    = yield :css
    = javascript_include_tag 'application'
    = yield :js
    = csrf_meta_tags
  body
    = render 'header'
    - if @full_screen_width
      = yield
    - else
      .container
        - if false
          - if alert
            .alert.alert-danger.alert-dismissible[role="alert"]
              button.close[type="button" data-dismiss="alert" aria-label="Close"]
                span[aria-hidden="true"]
                  | ×
              = alert
          - elsif notice
            .alert.alert-success.alert-dismissible[role="alert"]
              button.close[type="button" data-dismiss="alert" aria-label="Close"]
                span[aria-hidden="true"]
                  | ×
              = notice
        = yield
    = render 'footer'